on: workflow_dispatch

jobs:
  build:
    strategy: 
      matrix:
        board: [nissa, dedede, corsola, asurada, atlas, cherry, drallion, geralt, nocturne, rammus, rex, sarien, skyrim, staryu, eve]

    runs-on: ubuntu-latest
    steps:

      - name: download repo
        uses: actions/checkout@v4
      
      - name: run build
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler pv
          sudo apt-get install -y pv
          sudo pip3 install protobuf six --break-system-packages
          sudo QUIET=1 bash buildfull_badbr0ker.sh "${{ matrix.board }}"
      - name: upload img as artifact
        uses: actions/upload-artifact@v4
        with:
          name: badbr0ker${{ matrix.board }}.bin
          path: chromeos*.bin
          compression-level: 7
      - name: compress the disk image
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          sudo zip -9 badbr0ker_${{ matrix.board }}.zip chromeos*
      
      - name: create release
        uses: ading2210/gh-large-releases@main
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: badbr0ker*.zip
